<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<p><?php /* @escapeNotVerified */ echo __('Social Login') ?></p>
<!-- <table>
<tr>
	<th>User: </th>
	<td><input type="text" name=""></td>
</tr>
<tr>
	<th>Password: </th>
	<td><input type="password" name=""></td>
</tr>
</table>
 -->
 <button style="background-color: #1979c3; color: white; font-weight: bold; width: 156px;">FACEBOOK</button>
 <button>GMAIL</button>